server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://47.106.147.90:3306/tang_poetry?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: tangpoetry
#    eureka:
#      instance:
#        prefer-ip-address: true #注册时使用ip地址
#      client:
#        #      register-with-eureka: false # 不把自己注册到eureka上面
#        #      fetch-registry: false # 不从服务器上面来获取注册信息
#        service-url:
#          defaultZone: http://localhost:8761/eureka/



